service: geoip-lookup

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpackIncludeModules: true
  serverless-offline:
    port: 4566

package:
  individually: true

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1
  memorySize: 128

functions:
  geoipLookup:
    handler: src/geoipLookup.handler
    events:
      - http:
          path: /geoip
          method: GET
          cors: true
